package com.gxa.model;

import java.util.Date;

public class Client {


    @Override
    public String toString() {
        return "Client{" +
                "id=" + id +
                ", clientName='" + clientName + '\'' +
                ", realName='" + realName + '\'' +
                ", address='" + address + '\'' +
                ", auditingStatus=" + auditingStatus +
                ", type=" + type +
                ", districtId=" + districtId +
                ", code='" + code + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", accountId='" + accountId + '\'' +
                ", position='" + position + '\'' +
                ", signupTime=" + signupTime +
                ", lockingStatus=" + lockingStatus +
                ", deletingStatus=" + deletingStatus +
                ", bonusPoint=" + bonusPoint +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_name
     *
     * @mbg.generated
     */
    private String clientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.auditing_status
     *
     * @mbg.generated
     */
    private Integer auditingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.district_id
     *
     * @mbg.generated
     */
    private Integer districtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.phone_number
     *
     * @mbg.generated
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.account_id
     *
     * @mbg.generated
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.signup_time
     *
     * @mbg.generated
     */
    private Date signupTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.locking_status
     *
     * @mbg.generated
     */
    private Integer lockingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.deleting_status
     *
     * @mbg.generated
     */
    private Integer deletingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.bonus_point
     *
     * @mbg.generated
     */
    private Integer bonusPoint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.id
     *
     * @return the value of client.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.id
     *
     * @param id the value for client.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_name
     *
     * @return the value of client.client_name
     *
     * @mbg.generated
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_name
     *
     * @param clientName the value for client.client_name
     *
     * @mbg.generated
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.real_name
     *
     * @return the value of client.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.real_name
     *
     * @param realName the value for client.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.address
     *
     * @return the value of client.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.address
     *
     * @param address the value for client.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.auditing_status
     *
     * @return the value of client.auditing_status
     *
     * @mbg.generated
     */
    public Integer getAuditingStatus() {
        return auditingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.auditing_status
     *
     * @param auditingStatus the value for client.auditing_status
     *
     * @mbg.generated
     */
    public void setAuditingStatus(Integer auditingStatus) {
        this.auditingStatus = auditingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.type
     *
     * @return the value of client.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.type
     *
     * @param type the value for client.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.district_id
     *
     * @return the value of client.district_id
     *
     * @mbg.generated
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.district_id
     *
     * @param districtId the value for client.district_id
     *
     * @mbg.generated
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.code
     *
     * @return the value of client.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.code
     *
     * @param code the value for client.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.phone_number
     *
     * @return the value of client.phone_number
     *
     * @mbg.generated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.phone_number
     *
     * @param phoneNumber the value for client.phone_number
     *
     * @mbg.generated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.account_id
     *
     * @return the value of client.account_id
     *
     * @mbg.generated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.account_id
     *
     * @param accountId the value for client.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.position
     *
     * @return the value of client.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.position
     *
     * @param position the value for client.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.signup_time
     *
     * @return the value of client.signup_time
     *
     * @mbg.generated
     */
    public Date getSignupTime() {
        return signupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.signup_time
     *
     * @param signupTime the value for client.signup_time
     *
     * @mbg.generated
     */
    public void setSignupTime(Date signupTime) {
        this.signupTime = signupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.locking_status
     *
     * @return the value of client.locking_status
     *
     * @mbg.generated
     */
    public Integer getLockingStatus() {
        return lockingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.locking_status
     *
     * @param lockingStatus the value for client.locking_status
     *
     * @mbg.generated
     */
    public void setLockingStatus(Integer lockingStatus) {
        this.lockingStatus = lockingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.deleting_status
     *
     * @return the value of client.deleting_status
     *
     * @mbg.generated
     */
    public Integer getDeletingStatus() {
        return deletingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.deleting_status
     *
     * @param deletingStatus the value for client.deleting_status
     *
     * @mbg.generated
     */
    public void setDeletingStatus(Integer deletingStatus) {
        this.deletingStatus = deletingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.bonus_point
     *
     * @return the value of client.bonus_point
     *
     * @mbg.generated
     */
    public Integer getBonusPoint() {
        return bonusPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.bonus_point
     *
     * @param bonusPoint the value for client.bonus_point
     *
     * @mbg.generated
     */
    public void setBonusPoint(Integer bonusPoint) {
        this.bonusPoint = bonusPoint;
    }

}